name: FullStack CI CD

on:
  push:
    branches: [main]

jobs:

  # ─────────── DETECT CHANGES ───────────
  changes:
    runs-on: ubuntu-latest
    outputs:
      client: ${{ steps.filter.outputs.client }}
      admin: ${{ steps.filter.outputs.admin }}
      server: ${{ steps.filter.outputs.server }}

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            client:
              - 'Frontend/**'
            admin:
              - 'Admin/**'
            server:
              - 'Backend/**'

  # ─────────── CLIENT DEPLOY ───────────
  deploy-client:
    needs: changes
    if: ${{ needs.changes.outputs.client == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Client
        run: |
          cd client
          npm install

      - name: Build Client
        run: |
          cd client
          npm run build

      - name: Deploy Client to Netlify
        run: |
          npm install -g netlify-cli
          netlify deploy --prod \
            --dir=client/dist \
            --site=$CLIENT_SITE_ID
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOCKEN }}
          CLIENT_SITE_ID: ${{ secrets.NETLIFY_CLIENT_SITE_ID }}

  # ─────────── ADMIN DEPLOY ───────────
  deploy-admin:
    needs: changes
    if: ${{ needs.changes.outputs.admin == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Admin
        run: |
          cd admin
          npm install

      - name: Build Admin
        run: |
          cd admin
          npm run build

      - name: Deploy Admin to Netlify
        run: |
          npm install -g netlify-cli
          netlify deploy --prod \
            --dir=admin/dist \
            --site=$ADMIN_SITE_ID
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOCKEN }}
          ADMIN_SITE_ID: ${{ secrets.NETLIFY_ADMIN_SITE_ID }}

  # ─────────── BACKEND DEPLOY ───────────
  deploy-server:
    needs: changes
    if: ${{ needs.changes.outputs.server == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          cd Backend
          vercel --prod --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}










